version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    open-pull-requests-limit: 5
    labels:
      - "no changelog"
    assignees:
      - "robsdedude"
