[tox]
envlist = py{37,38,39,310,311,312,313,313t}-{test}
# for Python 3.7 support (https://github.com/tox-dev/tox/issues/3416#issuecomment-2426989929)
requires = virtualenv<20.22.0

[testenv]
deps = -r requirements-dev.txt
extras =
    numpy
    !py313t: pandas  # pandas is currently opting out of no-gil Python
    pyarrow
commands =
    test: python -m pytest -v --benchmark-skip {posargs} tests
