[tox]
envlist = py{310,311,312,313,314,314t,315,315t}-{test}-{releasedriver,devdriver}

[testenv]
passenv =
    TEST_*
    GITHUB_ACTIONS
    # [bump-pyarrow] search tag for when pyarrow supports Python 3.15
    # (env pass-through only needed when building wheel locally)
    PYARROW_WITH_*
dependency_groups =
    test
extras =
    numpy
    pandas
    pyarrow
commands_pre =
    devdriver: python -m pip install ./driver --no-deps
commands =
    test: python -m pytest -v --benchmark-skip {posargs} tests
