[tox]
envlist = py{310,311,312,313}-{test}-{releasedriver,devdriver}

[testenv]
dependency_groups =
    test
extras =
    numpy
    pandas
    pyarrow
commands_pre =
    devdriver: python -m pip install ./driver --no-deps
commands =
    test: python -m pytest -v --benchmark-skip {posargs} tests
